import { StyleSheet } from 'react-native';

const Css = StyleSheet.create({
  botao: {
    backgroundColor: 'black',
    alignItems: 'center',
    color: 'white',
    width: 250,
    margin: 10,
    padding: 15,
    borderRadius: 8,
  },
  botaoText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 18,
  },
  body: {
    backgroundColor: '#262626',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  body1: {
    backgroundColor: '#262626',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titulo: {
    textAlign: 'center',
    color: 'white',
    fontSize: 26,
    fontWeight: 700,
  },
  container: {
    marginTop: '1rem',
  },
  texto: {
    bottom: '8%',
  },
  caixaTexto: {
    backgroundColor: 'white',
    padding: 10,
    fontSize: 18,
    borderRadius: 10,
    marginVertical: 10,
    width: '90%',
    textAlign: 'center',
  },
  caixaResposata: {
    backgroundColor: 'tranparent',
    padding: 10,
    fontSize: 18,
    borderRadius: 10,
    marginVertical: 10,
    width: '90%',
    color: 'white',
    textAlign: 'center',
    border: '1px solid black',
  },
  grup: {
    flex: 1,
    flexDirection: 'row',
    width: '90%',
    justifyContent: 'space-between',
  },
  caixaTextoPequena: {
    backgroundColor: 'white',
    fontSize: 18,
    borderRadius: 10,
    marginVertical: 10,
    width: '6rem',
    height: '2.5rem',
    textAlign: 'center',
  },
  grup2: {
    flex: 1,
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
    marginTop: '-20rem',
  },
  caixaTextoMuitoPequena: {
    backgroundColor: 'white',
    fontSize: 18,
    borderRadius: 10,
    marginVertical: 10,
    width: '3.5rem',
    height: '2.5rem',
    textAlign: 'center',
  },
  grupT: {
    flex: 1,
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
  },
  grupT2: {
    flex: 1,
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
    marginTop: '-20rem',
  },
  caixaTextoPequena2: {
    backgroundColor: 'white',
    fontSize: 18,
    borderRadius: 10,
    marginVertical: 10,
    width: '8rem',
    height: '2.5rem',
    textAlign: 'center',
  },
  caixaTextoMuitoPequena2: {
    backgroundColor: 'white',
    fontSize: 18,
    borderRadius: 10,
    marginVertical: 10,
    width: '5rem',
    height: '2.5rem',
    textAlign: 'center',
  },
});
export { Css };
